import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Headings from "@/components/Headings";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
   title: "News-Now",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={`${inter.className} `}>
            <StoreProvider>
               <Navbar />
                  {children}
               <Footer />
            </StoreProvider>
         </body>
      </html>
   );
}
